id: I9C01C791
legacy_id: P003110
ocr_import_info:
  bdrc_scan_id: W22131
  source: bdrc
  ocr_info:
    timestamp: '2020-03-27T16:12:35'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-01T20:48:02.199878+00:00'
last_modified: 2022-09-02 04:48:09.525319
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W22131
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW22131
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: འདས་ལོག་བྱང་ཆུབ་སེངྒེའི་རྣམ་ཐར།
  author: ཉག་བླ་བྱང་ཆུབ་སེངྒེ
statistics:
  ocr_word_mean_confidence_index: 0.7983552910837376
  ocr_word_median_confidence_index: 0.8700000047683716
quality: null
bases:
  I3889:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3889
      total_pages: 280
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I3889.txt
    statistics:
      ocr_word_median_confidence_index: 0.8700000047683716
      ocr_word_mean_confidence_index: 0.7983552910837376
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
