id: I9C01C791
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T16:14:17+00:00'
last_modified: '2022-06-07T17:39:41.875400+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W22131
  title: འདས་ལོག་བྱང་ཆུབ་སེངྒེའི་རྣམ་ཐར།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    8B08:
      image_group_id: I3889
      title: ''
      total_pages: 280
      order: 1
      base_file: 8B08.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
